name: Update README

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up the script
        run: |
          chmod +x .github/workflows/update_age.sh
          .github/workflows/update_age.sh
      
      - name: Set up Git for GitHub          
        run: |
          git config user.name "automaton"
          git config user.email "automaton@github.com"
      
      - name: Create Pull Request or Commit to repository directly
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git add README.md
          git commit -m "Age mis à jour"
          git push https://x-access-token:${PAT}@github.com/Warckoooooo/Warckoooooo.git
