name: Update README

on:
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: pip install python-dateutil
      
      - name: Run update_age.py script
        run: python .github/workflows/update_age.py

      - name: Set up Git for GitHub
        run: |
          git config --global user.name "automaton"
          git config --global user.email "automaton@github.com"

      - name: Create Pull Request or Commit to repository directly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PAT: ${{ secrets.PAT }}
        run: |
          git add README.md
          if git diff-index --quiet HEAD; then
            echo "No changes detected."
          else
            git commit -m "Update Age"
            git push https://x-access-token:${PAT}@github.com/Warckoooooo/Warckoooooo.git || \
            (git fetch origin && \
            git rebase origin/main && \
            git push https://x-access-token:${PAT}@github.com/Warckoooooo/Warckoooooo.git)
